### PR TITLE
Add Contracts and DryTypes Includes Rubocop Rules

### PR DESCRIPTION
**Pull request by wpride**
This PR adds a couple of Rubocop rules/auto-corrections that we've used with good results at Flexport.

`PreferSorbetOverContracts`: forbids the creation of new [`Contract`s](https://github.com/egonSchiele/contracts.ruby) in favor of Sorbet signatures. Additionally, can convert most existing Contracts into Sorbet signatures automatically.

`NoDynamicContractIncludes`: the [`Dry::Types`](https://github.com/dry-rb/dry-types) library makes frequent use of dynamic includes to populate the name space with its types; so you use `include Dry::Types.module` and then can access `Strict::Int` or `Types::Array`. Since Sorbet does not allow dynamic includes, forbid this pattern. The Cop can also automatically remove the `include`s and replace with the static path IE `Dry::Types["strict.int"]`

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Actually, those libraries are open source, so we can include them here as well.

**Comment by wpride** [comment]
Updated PR description to be more explicative

**Comment by wpride** [comment]
@rafaelfranca Have you had a chance to consider this?

**Comment by wpride** [comment]
@paracycle Thank you for the response.

1. Yes, absolutely. We're using this at Flexport and will be happy to push forward our updates and receive any feedback. 
2. Done
3. Removed the one `puts` I could find - where are you seeing the logs?

**Comment by paracycle** [comment]
Thank you for your positive response and fixing some of the lint errors. 

However, I am afraid there are still [some lint errors left](https://travis-ci.org/Shopify/rubocop-sorbet/builds/588249485#L284). We have a pretty strict Ruby usage convention at Shopify that makes almost all parentheses mandatory (except for a few DSLs) and similar things. Those seem to be most of the linter errors left.

There is also [a test error](https://travis-ci.org/Shopify/rubocop-sorbet/builds/588249485#L498) which looks like a case of `Num` being expected instead of `Numeric`.

Finally, we will need you you to sign our CLA for this contribution please (lawyers, I'm afraid).

Thank you again. Looking forward to merging this.

**Comment by AlexEvanczuk** [comment]
Hey @wpride !

I am really excited about the auto-convert Contracts to Sorbet cop. Is there anyway I can help unblock this PR so that it could land? Are you still planning on continuing development on this?

**Comment by paracycle** [comment]
Hey @wpride, as I mentioned in my previous comment, we are looking forward to merging this after the tests have been fixed and the CLA has been signed. However, there hasn't been much progress in either of those topics recently, so I will be closing this PR to keep things tidy.

Please re-open if you want to continue the work and take it to the finishing line. Thanks!

**Pull request closed without merging**
